const I={
pl:{title:'🌟 Spoki — Twój mały asystent 🌟',idle:'Cześć! Naciśnij START, a będziemy rozmawiać 💜',start:'▶ START ROZMOWY',stop:'⏹ STOP',note:'Najlepiej działa w Chrome lub Edge. Rodzicu: kliknij START i pozwól na mikrofon 🎙️',heard:'Usłyszałam',mic:'🎙️ Rodzicu: pozwól na użycie mikrofonu',unsupported:'Ta przeglądarka nie obsługuje rozmowy głosowej — użyj przycisków 👇'},
en:{title:'🌟 Spoki — Your little helper 🌟',idle:'Hi! Press START and we can talk 💜',start:'▶ START TALKING',stop:'⏹ STOP',note:'Works best in Chrome or Edge. Grown-up: press START and allow the microphone 🎙️',heard:'I heard',mic:'🎙️ Grown-up: please allow the microphone',unsupported:'Voice recognition is unavailable — use the buttons below 👇'},
nl:{title:'🌟 Spoki — Jouw kleine helper 🌟',idle:'Hoi! Druk op START, dan gaan we praten 💜',start:'▶ START GESPREK',stop:'⏹ STOP',note:'Werkt het beste in Chrome of Edge. Ouder: druk op START en sta de microfoon toe 🎙️',heard:'Ik hoorde',mic:'🎙️ Ouder: sta de microfoon toe',unsupported:'Spraakherkenning is niet beschikbaar — gebruik de knoppen 👇'},
sw:{title:'🌟 Spoki — Msaidizi wako mdogo 🌟',idle:'Habari! Bonyeza ANZA, tuzungumze 💜',start:'▶ ANZA MAZUNGUMZO',stop:'⏹ SIMAMA',note:'Inafanya kazi vizuri katika Chrome au Edge. Mzazi: bonyeza ANZA na ruhusu maikrofoni 🎙️',heard:'Nimesikia',mic:'🎙️ Mzazi: tafadhali ruhusu maikrofoni',unsupported:'Utambuzi wa sauti haupatikani — tumia vitufe 👇'}
};
const L={
pl:{hello:['Cześć! Jestem Spoki! Jak masz na imię? 💜','Hej hej! Jestem Spoki! Co robimy?'],nameQ:'Jestem Spoki, twój mały pomocnik! A jak ty masz na imię? 😊',nameIs:n=>`${n}! Jakie śliczne imię! 💜`,fine:'Wspaniale! A ty? Pokaż duży uśmiech! 😄',askColor:'Jaki kolor najbardziej lubisz? 🎨',colorSay:c=>`Ładnie! ${c}! Super kolor! 🌈`,askFood:'Mniam! Co lubisz jeść? Ja lubię truskawki! 🍓',food:'Mniam, mniam! Pychota! 😋',count:'Liczę! Jeden, dwa, trzy, cztery, pięć, sześć, siedem, osiem, dziewięć, dziesięć! Brawo! 👏',song:'La, la, la, śpiewam sobie la! Słoneczko świeci, Spoki się śmieje! La, la, la! ☀️',dance:'Tańczymy! Wymachuj rączkami! Tupu, tupu! 💃',bye:'Papa! Do zobaczenia! Buziaczek! 😘',animalSay:s=>`Robi ${s}! `,askAnother:n=>`A jak robi ${n}? 🤔`,fallback:['Opowiedz mi o zwierzątkach! Jak robi piesek? 🐶','Policzmy razem! Powiedz: policz! 🔢','Chcesz piosenkę? Powiedz: zaśpiewaj! 🎵','Jaki kolor lubisz? 🎨'],chips:[['🐶','Piesek'],['🔢','Policz'],['🎵','Zaśpiewaj'],['🎨','Kolory'],['💃','Taniec'],['🍓','Jedzonko'],['👋','Papa']]},
en:{hello:["Hi! I'm Spoki! What's your name? 💜","Hello hello! I'm Spoki! What shall we do?"],nameQ:"I'm Spoki, your little helper! What's your name? 😊",nameIs:n=>`${n}! What a pretty name! 💜`,fine:"I'm great! Show me a big smile! 😄",askColor:"What's your favourite colour? 🎨",colorSay:c=>`${c}! Pretty colour! 🌈`,askFood:'Yummy! What do you like to eat? I love strawberries! 🍓',food:'Yum yum! Delicious! 😋',count:"Let's count! One, two, three, four, five, six, seven, eight, nine, ten! Yay! 👏",song:'La la la, I love to sing! The sun is shining, tra la la! ☀️',dance:"Let's dance! Wiggle wiggle! Stomp stomp! 💃",bye:'Bye bye! See you soon! Big kiss! 😘',animalSay:s=>`Says ${s}! `,askAnother:n=>`What does the ${n} say? 🤔`,fallback:['What does the dog say? 🐶',"Let's count! Say: count! 🔢",'Want a song? Say: sing! 🎵','What colour do you like? 🎨'],chips:[['🐶','Doggy'],['🔢','Count'],['🎵','Sing'],['🎨','Colours'],['💃','Dance'],['🍓','Yummy'],['👋','Bye bye']]},
nl:{hello:['Hoi! Ik ben Spoki! Hoe heet jij? 💜','Hallo hallo! Wat gaan we doen?'],nameQ:'Ik ben Spoki, jouw kleine helper! Hoe heet jij? 😊',nameIs:n=>`${n}! Wat een mooie naam! 💜`,fine:'Heel goed! Laat een grote lach zien! 😄',askColor:'Welke kleur vind jij het mooist? 🎨',colorSay:c=>`${c}! Mooie kleur! 🌈`,askFood:'Smullen! Wat eet jij graag? Ik hou van aardbeien! 🍓',food:'Jam jam! Lekker! 😋',count:'Ik tel! Een, twee, drie, vier, vijf, zes, zeven, acht, negen, tien! Goed zo! 👏',song:'La la la, ik zing een lied! De zon die schijnt, la la la! ☀️',dance:'We dansen! Zwaai met je armen! Stamp stamp! 💃',bye:'Dag dag! Tot ziens! Kusje! 😘',animalSay:s=>`Zegt ${s}! `,askAnother:n=>`En wat zegt de ${n}? 🤔`,fallback:['Wat zegt het hondje? 🐶','We tellen! Zeg: tel! 🔢','Wil je een liedje? Zeg: zing! 🎵','Welke kleur vind je mooi? 🎨'],chips:[['🐶','Hondje'],['🔢','Tel'],['🎵','Zing'],['🎨','Kleuren'],['💃','Dans'],['🍓','Eten'],['👋','Dag']]},
sw:{hello:['Habari! Mimi ni Spoki! Jina lako nani? 💜','Jambo jambo! Tufanye nini?'],nameQ:'Mimi ni Spoki, msaidizi wako mdogo! Jina lako nani? 😊',nameIs:n=>`${n}! Jina zuri sana! 💜`,fine:'Niko vizuri sana! Nionyeshe tabasamu! 😄',askColor:'Unapenda rangi gani? 🎨',colorSay:c=>`${c}! Rangi nzuri! 🌈`,askFood:'Ladha! Unapenda kula nini? Mimi napenda stroberi! 🍓',food:'Mmm! Tamu sana! 😋',count:'Tuhesabu! Moja, mbili, tatu, nne, tano, sita, saba, nane, tisa, kumi! Vizuri! 👏',song:'La la la, napenda kuimba! Jua linawaka, la la la! ☀️',dance:'Tucheze dansi! Sogeza mikono! 💃',bye:'Kwaheri! Tutaonana! Busu! 😘',animalSay:s=>`Anasema ${s}! `,askAnother:n=>`Na ${n} anasemaje? 🤔`,fallback:['Mbwa anasemaje? 🐶','Tuhesabu! Sema: hesabu! 🔢','Unataka wimbo? Sema: imba! 🎵','Unapenda rangi gani? 🎨'],chips:[['🐶','Mbwa'],['🔢','Hesabu'],['🎵','Imba'],['🎨','Rangi'],['💃','Dansi'],['🍓','Chakula'],['👋','Kwaheri']]}
};
const R={pl:'pl-PL',en:'en-GB',nl:'nl-NL',sw:'sw-KE'};
const animals={dog:{kw:['pies','piesku','dog','doggy','hond','mbwa'],noun:{pl:'piesek',en:'dog',nl:'hondje',sw:'mbwa'},sound:{pl:'hau hau',en:'woof woof',nl:'woef woef',sw:'woof woof'}},cat:{kw:['kot','kotek','cat','kitty','kat','paka'],noun:{pl:'kotek',en:'cat',nl:'kat',sw:'paka'},sound:{pl:'miau miau',en:'meow',nl:'miauw',sw:'meow'}},cow:{kw:['krow','cow','koe','ngombe'],noun:{pl:'krówka',en:'cow',nl:'koe',sw:"ng'ombe"},sound:{pl:'muuu',en:'moo',nl:'boe',sw:'moo'}},duck:{kw:['kacz','duck','eend','bata'],noun:{pl:'kaczuszka',en:'duck',nl:'eend',sw:'bata'},sound:{pl:'kwa kwa',en:'quack quack',nl:'kwak kwak',sw:'quack quack'}},lion:{kw:['lew','lion','leeuw','simba'],noun:{pl:'lew',en:'lion',nl:'leeuw',sw:'simba'},sound:{pl:'raaa',en:'roar',nl:'grrr',sw:'roar'}},frog:{kw:['zaba','frog','kikker','chura'],noun:{pl:'żabka',en:'frog',nl:'kikker',sw:'chura'},sound:{pl:'kum kum',en:'ribbit',nl:'kwaak kwaak',sw:'kwa kwa'}}};
const colors=['czerwony','niebieski','zielony','zolty','rozowy','fioletowy','red','blue','green','yellow','pink','purple','rood','blauw','groen','geel','roze','paars','nyekundu','bluu','kijani','njano','pinki','zambarau'];
let lang='pl',running=false,talking=false,restarting=false,hint=0,toastTimer;
const $=id=>document.getElementById(id),avatar=$('avatar'),bubble=$('bubble'),heard=$('heard'),startBtn=$('startBtn'),chips=$('chips'),toast=$('toast');
const norm=t=>(t||'').toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l').replace(/[^a-z0-9\s']/g,' ');
function showToast(text){clearTimeout(toastTimer);toast.textContent=text;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),3500)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=SR?new SR():null;
function stopRec(){restarting=false;if(rec)try{rec.abort()}catch{}avatar.classList.remove('listening')}
function startRec(){if(!rec||!running||talking||restarting)return;restarting=true;try{rec.lang=R[lang];rec.start();avatar.classList.add('listening')}catch{restarting=false}}
function voice(){const vs=speechSynthesis.getVoices();return vs.find(v=>v.lang.toLowerCase()===R[lang].toLowerCase())||vs.find(v=>v.lang.toLowerCase().startsWith(lang==='sw'?'sw':lang))||null}
function say(text,done){stopRec();bubble.textContent=text;if(!('speechSynthesis'in window)){done?.();return setTimeout(startRec,150)}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),v=voice();if(v)u.voice=v;u.lang=v?.lang||R[lang];u.pitch=1.2;u.rate=.9;let ended=false;const finish=()=>{if(ended)return;ended=true;talking=false;avatar.classList.remove('talking');done?.();setTimeout(startRec,180)};u.onstart=()=>{talking=true;avatar.classList.add('talking')};u.onend=finish;u.onerror=finish;speechSynthesis.speak(u)}
if(rec){rec.continuous=false;rec.interimResults=false;rec.onstart=()=>{restarting=false};rec.onresult=e=>{const t=e.results[e.results.length-1][0].transcript;if(!talking){heard.textContent=`💭 ${I[lang].heard}: ${t}`;respond(norm(t))}};rec.onend=()=>{restarting=false;avatar.classList.remove('listening');if(running&&!talking)setTimeout(startRec,250)};rec.onerror=e=>{restarting=false;if(e.error==='not-allowed'||e.error==='service-not-allowed'){showToast(I[lang].mic);stop()}else if(e.error==='language-not-supported')showToast(I[lang].unsupported)}}
function start(){running=true;startBtn.textContent=I[lang].stop;startBtn.classList.add('stop');heard.textContent='';renderChips();say(L[lang].hello[Math.floor(Math.random()*L[lang].hello.length)])}
function stop(){running=false;talking=false;window.speechSynthesis?.cancel();stopRec();avatar.classList.remove('talking');startBtn.textContent=I[lang].start;startBtn.classList.remove('stop')}
function respond(t){const x=L[lang];let m=t.match(/(?:mam na imie|nazywam sie|jestem|my name is|i am|ik heet|ik ben|ninaitwa|mimi ni)\s+([a-z]+)/i);if(m)return say(x.nameIs(m[1][0].toUpperCase()+m[1].slice(1)));if(/jak masz na imie|twoje imie|what.*your name|hoe heet jij|jina lako/.test(t))return say(x.nameQ);if(/papa|do widzenia|na razie|bye|goodbye|tot ziens|dag dag|kwaheri/.test(t))return say(x.bye);if(/co slychac|jak sie masz|how are you|hoe gaat het|habari/.test(t))return say(x.fine);if(/policz|licz|count|tel|tellen|hesabu/.test(t))return say(x.count);if(/zaspiewaj|piosenk|sing|song|zing|liedje|imba|wimbo/.test(t))return say(x.song);if(/tancz|taniec|dance|dans|dansi/.test(t))return say(x.dance);if(/kolor|colour|color|kleur|rangi/.test(t))return say(x.askColor);if(/jesc|jedzenie|jedzonko|mniam|eat|food|yummy|eten|lekker|kula|chakula/.test(t))return say(x.food);for(const [key,a] of Object.entries(animals))if(a.kw.some(w=>t.includes(norm(w)))){const next=Object.keys(animals).find(k=>k!==key);return say(x.animalSay(a.sound[lang])+x.askAnother(animals[next].noun[lang]))}for(const c of colors)if(t.includes(norm(c)))return say(x.colorSay(c));if(/czesc|hello|hej|dzien dobry|^hi$|hey|hoi|hallo|jambo|habari/.test(t))return say(x.hello[Math.floor(Math.random()*x.hello.length)]);say(x.fallback[hint++%x.fallback.length])}
const actions=[()=>say(L[lang].animalSay(animals.dog.sound[lang])+L[lang].askAnother(animals.cat.noun[lang])),()=>say(L[lang].count),()=>say(L[lang].song),()=>say(L[lang].askColor),()=>say(L[lang].dance),()=>say(L[lang].askFood),()=>say(L[lang].bye,()=>setTimeout(stop,400))];
function renderChips(){chips.replaceChildren(...L[lang].chips.map((c,i)=>{const b=document.createElement('button');b.className='chip';b.textContent=`${c[0]} ${c[1]}`;b.onclick=actions[i];return b}))}
function renderUi(){document.documentElement.lang=lang;$('title').textContent=I[lang].title;$('note').textContent=I[lang].note;startBtn.textContent=running?I[lang].stop:I[lang].start;if(!running)bubble.textContent=I[lang].idle;renderChips()}
startBtn.onclick=()=>running?stop():start();document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{stopRec();window.speechSynthesis?.cancel();talking=false;lang=b.dataset.lang;document.querySelectorAll('.lang').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderUi();if(running)say(L[lang].hello[0])});
renderUi();if(!rec)setTimeout(()=>showToast(I[lang].unsupported),700);if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
